name: UB24.04

on:
  push:
    paths-ignore:
      - '**/README.md'
      - '**/.gitignore'
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install mpich libtirpc-dev \
          python3-babel \
          python3-pytest-cython \
          python3-jinja2 \
          python3-pygments \
          python3-sphinx \
          python3-alabaster \
          libboost-all-dev \
          python3-certifi \
          python3-chardet \
          python3-click \
          cmake \
          libcppunit-dev \
          python3-docutils \
          doxygen \
          graphviz \
          libgraphviz-dev \
          libhdf5-dev \
          python3-idna \
          python3-imagesize \
          liblapack3 \
          liblapacke \
          liblapack-dev \
          liblapacke-dev \
          libxml2 \
          libxml2-dev \
          python3-markupsafe \
          libmetis5 \
          libmetis-dev \
          python3-mpi4py \
          python3-numpy \
          python3-packaging \
          python3-pyparsing \
          python3-tz \
          python3-requests \
          python3-scipy \
          python3-setuptools \
          python3-six \
          python3-stemmer \
          python3-sphinxcontrib.websupport \
          sphinx-intl \
          python3-urllib3 \
          libopenblas-dev

    - name: download and extract MEDCOUPLING
      run: |
        export MEDCOUPLING_VERSION=9.15.0
        export MEDCOUPLING_DIR=/home/runner/medcoupling
        wget -c --header="User-Agent: Mozilla/5.0 (X11; Linux x86_64)" \
          --header="Referer: https://www.salome-platform.org/" \
          https://files.salome-platform.org/Salome/Salome${MEDCOUPLING_VERSION}/MEDCOUPLING-${MEDCOUPLING_VERSION}-native-UB24.04-SRC.tar.gz \
          -O MEDCOUPLING-${MEDCOUPLING_VERSION}-native-UB24.04-SRC.tar.gz
        tar -xzf MEDCOUPLING-${MEDCOUPLING_VERSION}-native-UB24.04-SRC.tar.gz
        mv MEDCOUPLING-${MEDCOUPLING_VERSION}-native-UB24.04-SRC $MEDCOUPLING_DIR
    - name: test panda
      run: |
        cd poisson
        set +e                      # Don't exit immediately on failure
        export MEDCOUPLING_DIR=/home/runner/medcoupling
        source ${MEDCOUPLING_DIR}/env_launch.sh
        pytest -v
        status=$?                  # Capture exit code of pytest
        mkdir -p $GITHUB_WORKSPACE/artifacts
        find . \( -name "*.log" -o -name "*.txt" \) -exec cp --parents {} "$GITHUB_WORKSPACE/artifacts/" \; || true
        exit $status               # Re-raise make check's status to mark the step as failed if it should
    - name: Upload logs
      if: always()  # upload logs even if test failed
      uses: actions/upload-artifact@v4
      with:
        name: check-logs
        path: ${{ github.workspace }}/artifacts
